  
# add the linters you want stickler to use for this project
linters:
  stylelint:
    # indicate where is the config file for stylelint
    config: 'stylelint.config.js'

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

files:
    ignore:
       - 'styles/index.css'  #For ignoring a file/folder
fixers:
    enable: true   #This is the magic part of out fixing your errors